events {}

http {
  resolver 127.0.0.11 valid=5s ipv6=off;

  upstream app_backend {
    zone app_backend 64k;
    server app:3000 resolve;
  }

  server {
    listen 3000;
    server_name _;

    location / {
      proxy_pass http://app_backend;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
